# # This is a basic workflow to help you get started with Actions

name: Docker Actions

# # Controls when the action will run. 
on:
  pull_request:
    types: [labeled]

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  action:
    runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v1

      - name: hello-action
        uses: ./.github/actions/hello-world
      
      - name: meow
        uses: ./.github/actions/cat-facts
